name: pypipeline312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-image
  - scikit-learn
  - h5py
  - tifffile
  - roifile
  - tqdm
  - pip
  - pip:
    - opencv-python
